#!/usr/bin/env python3

"""
Phynteny: synteny-based annotation of phage genes
"""

import sys
import click
from phynteny_utils import handle_genbank
from phynteny_utils import predictor
from Bio import SeqIO
import pkg_resources 

__author__ = "Susanna Grigson"
__maintainer__ = "Susanna Grigson"
__license__ = "MIT"
__version__ = "0"
__email__ = "susie.grigson@gmail.com"
__status__ = "development"

@click.command()
@click.argument("infile", type=click.Path(exists=True))
@click.option(
    "-o",
    "--outfile", 
    type=click.Path(), 
    help="where to write the output genbank file",
)
@click.option(
    "-m",
    "--model",
    type=click.Path(exists=True),
    help="Path to custom LSTM model",
    default=pkg_resources.resource_filename('phynteny_utils', 'test_model'),
)
@click.option(
    "-t",
    "--threshold",
    type=int,
    help="Threshold phynteny score to use as a cutoff",
    default=5
)
@click.version_option(version=__version__)

def main(infile, outfile, model, threshold):
    """
    Phynteny: synteny-based annotation of phage genes
    """

    # get the absolute paths to phrog annotation files, model and thresholds 
    phrog_categories = pkg_resources.resource_filename('phynteny_utils', 'phrog_annotation_info/phrog_integer.pkl')
    category_names = pkg_resources.resource_filename('phynteny_utils', 'phrog_annotation_info/integer_category.pkl')
    
    # get entries in the genbank file
    gb_dict = handle_genbank.get_genbank(infile)
    if not gb_dict:
        click.echo("Error: no sequences found in genbank file")
        sys.exit()
    keys = list(gb_dict.keys())

    # create predictor object
    gene_predictor = predictor.Predictor(model, phrog_categories, threshold, category_names)

    # Run Phynteny
    with click.open_file(outfile, "wt") if outfile else sys.stdout as handle:

        for key in keys:

            print('Annotating the phage: ' + key, flush=True) 

            # get current phage
            phages = {key: handle_genbank.extract_features(gb_dict.get(key))}

            # get phrog annotations
            phages[key]["phrogs"] = [
                0 if i == "No_PHROG" else int(i) for i in phages[key]["phrogs"]
            ]

            # make predictions
            phynteny = gene_predictor.predict_annotations(phages)

            # update with these annotations
            cds = [i for i in gb_dict.get(key).features if i.type == "CDS"]
            for i in range(len(cds)):
                cds[i].qualifiers["phynteny"] = phynteny[i]

            # write to genbank file
            SeqIO.write(gb_dict.get(key), handle, "genbank") 

    if outfile: 
        print('DONE') 

if __name__ == "__main__":
    main()

